### ISSUE TITLE
CPAN Pull request challenge

### ISSUE THREAD

**Issue by sdeseille** [Manwar/XML-XPath#1]
Hello

I joined the "CPAN Pull Request Challenge" and Neil Bowers ask me to make a Pull Request on your module "XML::XPath".

Is there anything i can do to be helpful ?

regards

sdeseille

**Comment by Manwar** [comment]
Hi @sdeseille,

Thanks for your offer.

I would love to have your help in fixing some of the outstanding issues as listed here:
https://rt.cpan.org/Dist/Display.html?Name=XML-XPath

specially this one:
https://rt.cpan.org/Ticket/Display.html?id=11724

Please give me a shout back if you have any questions.

Best Regards,
Mohammad S Anwar

**Comment by sdeseille** [comment]
Hi 

Thanks for your answer.
I start to work on that.

regards

sdeseille

**Comment by Manwar** [comment]
Thanks for your contribution.
