### ISSUE TITLE
Wrong abstract is used by MetaCPAN because it's not set in Makefile.PL

### ISSUE THREAD

**Issue by y** [manwar/XML-XPath#5]
The Makefile.PL needs to set the ABSTRACT_FROM field so the right abstract is used. Look at the META.yml or META.json files and you'll see it's set to unknown because it doesn't know where to extract it from. The MetaCPAN site tries to determine the abstract on it's own, but extracts it from the xpath example script instead.

**Comment by manwar** [comment]
Good catch, will fix in the next release, may be tomorrow.

**Comment by manwar** [comment]
XML::XPath v1.42 released to patch the issue #5.

**Comment by manwar** [comment]
Closing the issue now as it has been fixed.
